spring:
  application:
    name: mailer-spring
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: mailer-spring
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-mode: record

kafka:
  topic:
    verification: ${KAFKA_TOPIC_VERIFICATION:auth.email.verification.request}
